-- Tabela para controle de numeração sequencial de NFCe por loja e série
CREATE TABLE IF NOT EXISTS public.nfce_sequences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    serie INTEGER NOT NULL DEFAULT 1,
    last_number INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(organization_id, serie)
);

-- Habilitar RLS
ALTER TABLE public.nfce_sequences ENABLE ROW LEVEL SECURITY;

-- Política para leitura
CREATE POLICY "Permitir leitura para membros da mesma org" ON public.nfce_sequences
    FOR SELECT
    USING (organization_id IN (
        SELECT organization_id FROM public.profiles WHERE id = auth.uid()
    ));

-- Política para inserção/update
CREATE POLICY "Permitir alteração para membros da mesma org" ON public.nfce_sequences
    FOR ALL
    USING (organization_id IN (
        SELECT organization_id FROM public.profiles WHERE id = auth.uid()
    ));

-- Função para atualizar o updated_at
CREATE OR REPLACE FUNCTION public.handle_nfce_sequences_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_nfce_sequences_updated
    BEFORE UPDATE ON public.nfce_sequences
    FOR EACH ROW EXECUTE FUNCTION public.handle_nfce_sequences_updated_at();

-- Seed inicial para NHT (Norberto) - Iniciando na Série 2
INSERT INTO public.nfce_sequences (organization_id, serie, last_number)
VALUES ('7b2d3a85-de90-4e57-adb7-91102c11094a', 2, 0)
ON CONFLICT (organization_id, serie) DO NOTHING;

-- Função RPC para obter e incrementar o próximo número de forma atômica
CREATE OR REPLACE FUNCTION public.get_next_nfce_number(p_org_id UUID, p_serie INTEGER)
RETURNS INTEGER AS $$
DECLARE
    v_next_number INTEGER;
BEGIN
    -- Incrementa e retorna o novo valor em uma única operação atômica
    UPDATE public.nfce_sequences
    SET last_number = last_number + 1
    WHERE organization_id = p_org_id AND serie = p_serie
    RETURNING last_number INTO v_next_number;

    -- Se não encontrar o registro, cria um novo (Série 1, começa no 1)
    IF v_next_number IS NULL THEN
        INSERT INTO public.nfce_sequences (organization_id, serie, last_number)
        VALUES (p_org_id, p_serie, 1)
        ON CONFLICT (organization_id, serie) 
        DO UPDATE SET last_number = public.nfce_sequences.last_number + 1
        RETURNING last_number INTO v_next_number;
    END IF;

    RETURN v_next_number;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

